services:
  - type: web
    name: kea-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: JWT_SECRET
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: VOTE_PRICE
        value: 20
      - key: SPONSOR_DAY_PRICE
        value: 50000
      - key: MAX_FREE_VOTES_PER_PERSON
        value: 2
